version: 1.0.0

_config: merge

approve:
  include:
    branches:
      dependabot_maven:
        prefix: "dependabot/maven"

merge:
  include:
    branches:
      dependabot_maven:
        prefix: "dependabot/maven"
  method: squash
