FROM eclipse-temurin:17-jdk-jammy

# protobuf-compiler needed to compile the generated code for the .proto files
# iproute2 needed for the testcontainers to work within a container (DIND)
RUN apt update && \
  apt -y upgrade && \
  apt -y install protobuf-compiler iproute2 && \
  apt -y autoremove && \
  apt -y clean && \
  rm -rf /var/lib/apt/lists/*
